---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        ports:
        - containerPort: 5775
          protocol: UDP
          name: zipkin-compact
        - containerPort: 6831
          protocol: UDP
          name: jaeger-compact
        - containerPort: 6832
          protocol: UDP
          name: jaeger-binary
        - containerPort: 5778
          protocol: TCP
          name: config-rest
        - containerPort: 16686
          protocol: TCP
          name: ui
        - containerPort: 4317
          protocol: TCP
          name: otlp-grpc
        - containerPort: 4318
          protocol: TCP
          name: otlp-http
        - containerPort: 14250
          protocol: TCP
          name: jaeger-grpc
        - containerPort: 14268
          protocol: TCP
          name: jaeger-http
        - containerPort: 9411
          protocol: TCP
          name: zipkin
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: jaeger
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
  - port: 5775
    protocol: UDP
    targetPort: 5775
    name: zipkin-compact
  - port: 6831
    protocol: UDP
    targetPort: 6831
    name: jaeger-compact
  - port: 6832
    protocol: UDP
    targetPort: 6832
    name: jaeger-binary
  - port: 5778
    protocol: TCP
    targetPort: 5778
    name: config-rest
  - port: 16686
    protocol: TCP
    targetPort: 16686
    name: ui
  - port: 4317
    protocol: TCP
    targetPort: 4317
    name: otlp-grpc
  - port: 4318
    protocol: TCP
    targetPort: 4318
    name: otlp-http
  - port: 14250
    protocol: TCP
    targetPort: 14250
    name: jaeger-grpc
  - port: 14268
    protocol: TCP
    targetPort: 14268
    name: jaeger-http
  - port: 9411
    protocol: TCP
    targetPort: 9411
    name: zipkin
  selector:
    app: jaeger
